version: '3'
services:
  backend:
    image: caochientp1/knowled:latest
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'

  redis:
    image: redis:6.0
    restart: always
    ports:
      - 6379:6379